baseurl = "https://themilkshelf.com/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
theme = "hugo-tracks-theme"
title = "The Milk Shelf MN"
[params]
copyright = "&copy;2016 The Milk Shelf"
description = "Describe your website"
email = "you@yoursite.com"
sidebarabout = ["TheMilkShelfMN Sidebar"]
style = "default"
[params.social]
facebook = "https://www.facebook.com/TheMilkShelfMN/"
[[params.navlinks]]
name = "Home"
url = ""
[[params.navlinks]]
name = "About"
url = "about/"
[[params.navlinks]]
name = "Get in touch"
url = "contact/"
